# Generated by Django 2.1.1 on 2018-09-27 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('dob', models.DateTimeField()),
                ('email', models.CharField(max_length=25)),
                ('fathers_name', models.CharField(max_length=30)),
                ('mothers_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=12)),
                ('nationality', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('no_of_family_member', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloted_jail', models.CharField(max_length=20)),
                ('crime', models.CharField(max_length=20)),
                ('crime_date', models.DateTimeField()),
                ('police_act', models.CharField(max_length=25)),
                ('punishment', models.CharField(max_length=30)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('is_authorised', models.BooleanField()),
                ('is_activated', models.BooleanField()),
                ('designation', models.CharField(max_length=20)),
                ('police_station', models.CharField(max_length=25)),
            ],
        ),
    ]
